#!/bin/sh

### BEGIN INIT INFO
# Provides:          piplanepicture
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop piplanepicture.
# Description:       This script starts/stops piplanepicture.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

OPTS="/home/pi/share/piplanepicture.py"
LOG=/home/pi/share/log/piplanepicture.out

res=0

case "$1" in
  start)
        echo "Starting: piplanepicture" >&2
        /usr/bin/python $OPTS >> $LOG 2>&1
        ;;

  restart|force-reload)
        $0 stop
        sleep 1
        $0 start
        ;;

  stop)
        echo "Stopping: piplanepicture" >&2
        killall python
        killall dump1090
        ;;

  status)
        ;;

  *)
        echo "Usage: piplanepicture [start|stop|status]" >&2
        res=3
        ;;
esac

exit $res
